name: Feature Request
description: File a feature request.
title: "[Feature]: "
labels: ["feature", "enhancement"]
projects: ["rudziktv/8"]
assignees:
  - rudziktv
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: Request
      description: Tell us what behaviour you expect from our application.
      placeholder: I want your application to do something...
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behaviour
      description: If function exists, but you want to enhance it, tell us what is current behaviour of this feature.
      placeholder: Currently your app doesn't support...
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - dev-preview-demo
      default: 0
    validations:
      required: true
  - type: textarea
    id: example-code
    attributes:
      label: Proposal code
      description: If you don't want to contribute it yourself, you can propose here change in source, some code, pseudocode etc. 
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
